version: '3.8'

services:
  arxivflow-prefect-server:
    build:
      context: ./docker/prefect-server
      dockerfile: Dockerfile
    command: prefect server start --host 0.0.0.0
    ports:
      - '4200:4200'
    env_file:
      - .env
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL_SERVER}
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'curl -f ${PREFECT_API_URL_SERVER}/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10

  arxivflow-prefect-agent:
    build:
      context: .
      dockerfile: ./Docker/prefect-agent/Dockerfile
    env_file:
      - .env
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL_AGENT}
    volumes:
      - ${LOCAL_PERSIST_DIRECTORY}:${PERSIST_DIRECTORY}
    restart: always
    depends_on:
      arxivflow-prefect-server:
        condition: service_healthy

  minio:
    image: minio/minio
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      backend-net:
        aliases:
          - ${MINIO_HOST}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - backend-net
    environment:
      - HOST=0.0.0.0
      - REACT_APP_MINIO_HOST=${MINIO_HOST}
    env_file:
      - .env
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - backend-net
    depends_on:
      - minio
    env_file:
      - .env
    volumes:
      - ${LOCAL_PERSIST_DIRECTORY}:${PERSIST_DIRECTORY}
    restart: always

volumes:
  minio_data:

networks:
  backend-net:
    driver: bridge
