FROM minio/minio

# Copier le fichier CORS et le script d'entrypoint dans l'image
COPY minio/cors.xml /cors.xml
COPY minio/entrypoint.sh /entrypoint.sh

# Rendre le script exécutable
RUN chmod +x /entrypoint.sh

# Définir les variables d'environnement par défaut (adaptables via docker-compose)
ENV MINIO_ROOT_USER=minioadmin
ENV MINIO_ROOT_PASSWORD=minioadmin

# Remplacer l'entrypoint par le script personnalisé
ENTRYPOINT ["/entrypoint.sh"]
