version: '3.8'

services:
  arxivflow-prefect-server:
    build:
      context: .
      dockerfile: Dockerfile.prefect-server
    command: prefect server start --host 0.0.0.0
    ports:
      - '4200:4200'
    env_file:
      - .env
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL_SERVER}
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'curl -f ${PREFECT_API_URL_SERVER}/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10

  arxivflow-prefect-agent:
    build: .
    env_file:
      - .env
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL_AGENT}
    volumes:
      - ${LOCAL_PERSIST_DIRECTORY}:${PERSIST_DIRECTORY}
    restart: always
    depends_on:
      arxivflow-prefect-server:
        condition: service_healthy

  minio:
    image: minio/minio
    env_file:
      - .env
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  minio_data:
